# agem/git_committer.py
import os
import subprocess
from datetime import datetime
from typing import List, Any
from dataclasses import dataclass


@dataclass
class CommitResult:
    success: bool
    branch: str
    commit_hash: str
    message: str


class GitCommitter:
    def __init__(self, repo_path: str = "."):
        self.repo_path = repo_path
        self.branch_prefix = "agem/auto-optimize"
    
    def _run_git(self, args: List[str]) -> subprocess.CompletedProcess:
        return subprocess.run(["git"] + args, cwd=self.repo_path, capture_output=True, text=True)
    
    def commit_patch(self, patch: Any, resource_name: str) -> CommitResult:
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        branch_name = f"{self.branch_prefix}-{resource_name}-{timestamp}"
        
        self._run_git(["stash", "push", "-m", "agem-temp"])
        result = self._run_git(["checkout", "-b", branch_name])
        if result.returncode != 0:
            self._run_git(["checkout", "main"])
            result = self._run_git(["checkout", "-b", branch_name])
            if result.returncode != 0:
                return CommitResult(False, "", "", f"Failed to create branch: {result.stderr}")
        
        patch_file = f"patch-{resource_name}-{timestamp}.md"
        patch_content = f"""# AGEM Optimization Patch

**Resource:** {patch.resource_name}
**Type:** {patch.resource_type}
**Action:** {patch.action}
**Estimated Savings:** {patch.estimated_savings}


## Proposed Change

## Rollback

Generated by AGEM at {datetime.now().isoformat()}
"""
        
        with open(os.path.join(self.repo_path, patch_file), "w") as f:
            f.write(patch_content)
        
        self._run_git(["add", patch_file])
        commit_msg = f"agem: optimize {resource_name}\\n\\n{patch.action}\\nSavings: {patch.estimated_savings}"
        result = self._run_git(["commit", "-m", commit_msg])
        
        if result.returncode != 0:
            return CommitResult(False, branch_name, "", f"Commit failed: {result.stderr}")
        
        hash_result = self._run_git(["rev-parse", "HEAD"])
        commit_hash = hash_result.stdout.strip()
        self._run_git(["checkout", "main"])
        self._run_git(["stash", "pop"])
        
        return CommitResult(True, branch_name, commit_hash, f"Committed to {branch_name}")
    
    def list_branches(self) -> List[str]:
        result = self._run_git(["branch", "-a"])
        branches = []
        for line in result.stdout.split("\\n"):
            line = line.strip().replace("* ", "")
            if self.branch_prefix in line:
                branches.append(line)
        return branches
