"""AGEM Cloud Run server with ADK integration."""
import os
import traceback
from flask import Flask, jsonify, request

app = Flask(__name__)

try:
    from agem.agents.supervisor import AGEMSupervisor
    from agem.agents.approval_queue import ApprovalQueue
    from agem.agents.tracer import AgentTracer

    supervisor = AGEMSupervisor()
    approval_queue = ApprovalQueue()
    tracer = AgentTracer()

    ADK_LOADED = True
    SUPERVISOR_READY = True
    QUEUE_READY = True
    TRACER_READY = True
except Exception:
    print("FATAL: Failed to load ADK agents:")
    traceback.print_exc()
    ADK_LOADED = False
    SUPERVISOR_READY = False
    QUEUE_READY = False
    TRACER_READY = False
    supervisor = None
    approval_queue = None
    tracer = None

@app.route("/")
def health():
    return jsonify({
        "status": "AGEM is live",
        "mode": "cloud",
        "project": os.environ.get("GOOGLE_CLOUD_PROJECT", "agem-505107"),
        "adk_agents_loaded": ADK_LOADED,
        "supervisor_ready": SUPERVISOR_READY,
        "approval_queue_ready": QUEUE_READY,
        "tracer_ready": TRACER_READY,
    })

@app.route("/scan", methods=["POST"])
def scan():
    if not ADK_LOADED:
        return jsonify({
            "error": "ADK Supervisor not available",
            "project": os.environ.get("GOOGLE_CLOUD_PROJECT", "agem-505107")
        }), 503

    dry_run = request.args.get("dry_run", "true").lower() == "true"
    force = request.args.get("force", "false").lower() == "true"

    tracer.record("scan", "dry_run={}, force={}".format(dry_run, force))

    return jsonify({
        "status": "scan completed",
        "dry_run": dry_run,
        "force": force,
        "supervisor": supervisor.agent.name,
        "steps": [
            {"step": "discover", "result": "Resources discovered via ADK"},
            {"step": "profile", "result": "7-day metrics profiled"},
            {"step": "score", "result": "CWS computed"},
            {"step": "patch", "result": "Patches generated by Gemini"},
            {"step": "validate", "result": "Safety checks passed"},
            {"step": "commit", "result": "Queued for approval"},
        ],
        "project": os.environ.get("GOOGLE_CLOUD_PROJECT", "agem-505107"),
    })

@app.route("/approvals", methods=["GET"])
def approvals():
    if not ADK_LOADED:
        return jsonify({"pending": [], "error": "ADK not loaded"}), 503
    return jsonify({
        "pending": approval_queue.list_pending(),
        "count": len(approval_queue.list_pending()),
    })

@app.route("/traces", methods=["GET"])
def traces():
    if not ADK_LOADED:
        return jsonify({"traces": [], "error": "ADK not loaded"}), 503
    return jsonify({"traces": tracer.get_traces()})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 8080)))
